version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SERVER_ID=${SERVER_ID}
      - CHANNEL_ID=${CHANNEL_ID}
